config/routes.rb
Rails.application.routes.draw do

  # root "folders#show"
  # root to: "folders#show", permalink: "unread"

  root to: redirect('/folder/unread')

  # devise_for :user
  devise_for :user,
  controllers: {
    registrations: 'users/registrations'
  },
  path: "",
  path_names: {
    sign_in: "login",
    sign_out: "logout",
    sign_up: "register",
    edit: "settings"
  }

  # get '/user', to: redirect('/folder/unread')

  get "folder/:permalink" => "folders#show", as: "folder_permalink"
  get "folder/:permalink/download" => "folders#download", as: "download_folder"
  patch "folder/:id/archive-all" => "folders#archive_all", as: "archive_all"
  resources :folders, path: "/folder" do
    member do
      patch :sort
    end
  end

  # get "article/new" => "article#create", as: "new_article"
  # delete "article/:permalink" => "article#destroy", as: "delete_article"
  # patch "article/:permalink/archive" => "article#archive", as: "archive_article"
  # patch "article/:permalink/unarchive" => "article#unarchive", as: "unarchive_article"
  resources :articles, path: "/article" do
    member do
      patch :archive
      patch :unarchive
    end
  end
  # resources :articles, only: [:index]
  get "export" => "articles#export", as: "export"

  namespace :hello, defaults: { format: 'js' } do
    # resources :articles
    get ":hello_token" => "articles#index"
    post ":hello_token" => "articles#create"
  end

  post "billing", to: "billing#create", as: "billing_create"
  post "billing/edit", to: "billing#edit", as: "billing_edit"
  resources :webhooks, only: [:create]

end

app/models/folder.rb
class Folder < ApplicationRecord

  before_save :set_permalink

  before_destroy :destroy_articles
  belongs_to :user
  has_many :articles

  validates :name, presence: true, uniqueness: { scope: :user_id }

  def to_param
    permalink
  end

  private

    def set_permalink
      self.permalink = name.parameterize
    end

    def destroy_articles
      self.articles.destroy_all
    end

end

app/controllers/folders_controller.rb
require 'httparty'
require 'nokogiri'

class FoldersController < ApplicationController
  include Pagy::Backend

  before_action :authenticate_user!
  before_action :set_folder, only: [:edit, :update, :destroy]

  # GET /folders
  # GET /folders.json
  def index
    @folders = Folder.where.not(permalink: 'unread').where.not(permalink: 'archive')
  end

  # GET /folders/:permalink
  # GET /folders/:permalink.json
  def show
    folder_id = Folder.find_by_permalink(params[:permalink]).id
    @folder = Folder.find(folder_id)

    if params[:controller] == 'folders' && params[:action] == 'show' && params[:permalink] == 'archive'
      @pagy, @articles = pagy(current_user.articles.left_outer_joins(:folder).where(folder: { permalink: params[:permalink] }).order(created_at: :desc), items: 50)
    else
      # @pagy, @folders = pagy(Folder.all, items: 50)
      @pagy, @articles = pagy(current_user.articles.left_outer_joins(:folder).where(folder: { permalink: params[:permalink] }).order(position: :asc), items: 50)
    end
  end

  # GET /folders/new
  # def new
  #   @folder = Folder.new
  # end

  # GET /folders/:permalink/edit
  def edit
    render
  end

  # POST /folders
  # POST /folders.json
  def create
    @folder = Folder.new
    @folder.user_id = current_user.id
    @folder.name = params[:name]
    @folder.save!
    redirect_back(fallback_location: folder_path("unread"))
  end

  # PATCH/PUT /folders/1
  # PATCH/PUT /folders/1.json
  def update
    respond_to do |format|
      if @folder.update(folder_params)
        format.html { redirect_to @folder, notice: 'Folder was successfully updated.' }
        format.json { render :show, status: :ok, location: @folder }
      else
        format.html { render :edit }
        format.json { render json: @folder.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH /folders/:permalink/sort
  def sort
    params[:articles].split(',').map.with_index do |id, position|
      current_user.articles.find_by_id(id).update_columns(position: position)
    end
    head :ok
  end

  # PATCH /folders/:id/archive-all
  def archive_all
    archive_folder = Folder.where(name: "Archive", user_id: current_user.id).first_or_create

    params[:articles].split(',').map.with_index do |id, position|
      current_user.articles.find_by_id(id).update_columns(folder_id: archive_folder.id)
    end

    respond_to do |format|
      format.js { render inline: "location.reload();" }
    end

  end

  # GET /folders/:permalink/download
  def download
    current_user.update(download_failed: nil) unless current_user.download_failed == nil
    folder = Folder.find(current_user.folders.find_by_permalink(params[:permalink]).id)
    # DownloadJob.perform_later(current_user, folder)

    # TODO: Make a environment variable check to use the Job with redirect only
    # in production.

    # When unknown errors arise, comment-out the DownloadJob call above, and
    # use the below for better error reporting
    articles = current_user.articles.left_outer_joins(:folder).where(folder: folder)
    ebook = Download.new(current_user, articles)
    ebook.download
    TableOfContents.create("#{ebook.full_directory_path}/toc.html", ebook.files)
    # fail
    ebook_file_name = "Portholes-#{folder.name.parameterize(preserve_case: true)}-#{Date.today.to_s}"
    unless current_user.ebook_preference == 'epub'
      EbookCreator.kindle(current_user, ebook.user_directory, ebook.full_directory_path, ebook_file_name, folder)
    else
      EbookCreator.epub(current_user, ebook.user_directory, ebook.full_directory_path, ebook_file_name, folder)
    end

    redirect_to edit_user_registration_path, notice: 'Your download is processing. You will need to refresh this page to see it in the downloads section below.'
  end

  # DELETE /folders/:permalink
  # DELETE /folders/:permalink.json
  def destroy
    archive_folder = Folder.where(name: "Archive", user_id: current_user.id).first_or_create
    articles_in_folder = current_user.articles.where(folder: @folder)

    unless articles_in_folder.empty?
      articles_in_folder.map do |article|
        current_user.articles.find(article.id).update_columns(folder_id: archive_folder.id)
      end
    end

    @folder.destroy
    respond_to do |format|
      format.html { redirect_to folder_path("unread"), notice: "The folder \"#{@folder.name}\" has been deleted." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_folder
      @folder = Folder.find_by_permalink(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def folder_params
      params.require(:folder).permit(:name, :permalink, :user_id)
    end
end

app/helpers/folders_helper.rb
module FoldersHelper

  def downloadable_folder?
    return true if params[:controller] == 'folders' && params[:action] == 'show' && request.path != '/folder/archive'
  end

  def default_folder?
    return true if request.path == '/folder/unread' || request.path == '/folder/archive'
  end

  def sidebar_folders
    current_user.folders.where.not(name: ["Unread","Archive"])
  end

end

app/views/folders/_form.html.erb
<%= form_with(model: folder, local: true, class: 'folder-edit') do |form| %>
  <% if folder.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(folder.errors.count, "error") %> prohibited this folder from being saved:</h2>

      <ul>
        <% folder.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="d-flex justify-content-between">
    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>
    <%= form.submit %>
  </div>

  <div class="d-none field">
    <%= form.label :user_id %>
    <%= form.hidden_field :user_id %>
  </div>
<% end %>

app/views/folders/_sidebar.html.erb
<aside class="sidebar">
  <nav class="widget">
    <%= link_to folder_path("unread"), class: ("active" if current_page?(folder_path("unread"))), itemprop: "url" do %><%= inline_svg('home.svg') %>Unread<% end %>
    <%= link_to folder_path("archive"), class: ("active" if current_page?(folder_path("archive"))), itemprop: "url" do %><%= inline_svg('archive.svg') %>Archive<% end %>
    <% Array(sidebar_folders).each do |folder| %>
      <%= link_to folder_path(folder.permalink), class: ("active" if current_page?(folder_path(folder.permalink))), itemprop: "url" do %><%= inline_svg('folder-open-solid.svg') %><%= folder.name %><% end %>
    <% end %>
    <%= form_with(url: folders_path, id: 'new-folder') do |form| %>
      <%= inline_svg('folder-open-solid.svg') %>
      <%= form.label :name, class: "screen-reader-text" %>
      <%= form.text_field :name, placeholder: "Add Folder" %>
      <%= form.submit %>
    <% end %>
  </nav>
</aside>

app/views/folders/edit.html.erb
<% if current_user %>

  <%= render 'sidebar', folder: @folder %>

  <main class="main">
    <h1>Edit <%= @folder.name %></h1>

    <%= render 'form', folder: @folder %>
    <%= link_to 'Delete Folder', @folder, method: :delete, data: { confirm: "Are you sure you want to permanently delete this folder?" }, class: "button danger" %>
  </main>

<% else %>
  <main class="main">
    <%= render "layouts/signin" %>
  </main>
<% end %>

app/views/folders/index-bk.html.erb
<p id="notice"><%= notice %></p>

<h1>Folders</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Permalink</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @folders.each do |folder| %>
      <tr>
        <td><%= folder.name %></td>
        <td><%= folder.permalink %></td>
        <td><%= folder.user_id %></td>
        <td><%= link_to 'Show', folder %></td>
        <td><%= link_to 'Edit', edit_folder_path(folder) %></td>
        <td><%= link_to 'Destroy', folder, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Folder', new_folder_path %>

app/views/folders/index.html.erb
<% if current_user %>

  <%= render 'sidebar', folder: @folder %>

  <main class="main">
    <h1>Your Folders</h1>
    <% @folders.each do |folder| %>
      <div class="article">
        <div class="sort-title-wrapper">
          <div class="folder">
            <%= inline_svg("folder-open-solid.svg") %>
          </div>
          <div class="title-wrapper">
            <p class="title"><%= folder.name %></p>
          </div>
        </div>
        <div class="archive-delete-wrapper">
          <%= link_to inline_svg("edit-solid.svg"), edit_folder_path(folder) %>
          <%= link_to inline_svg("trash.svg"), folder, method: :delete, data: { confirm: "Are you sure you want to permanently delete this folder?" }, class: "delete" %>
        </div>
      </div>
    <% end %>
  </main>

<% else %>
  <main class="main">
    <%= render "layouts/signin" %>
  </main>
<% end %>

app/views/folders/new.html.erb
<h1>New Folder</h1>

<%= render 'form', folder: @folder %>

<%= link_to 'Back', folders_path %>

app/views/folders/show-bk.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @folder.name %>
</p>

<p>
  <strong>Permalink:</strong>
  <%= @folder.permalink %>
</p>

<p>
  <strong>User:</strong>
  <%= @folder.user_id %>
</p>

<%= link_to 'Edit', edit_folder_path(@folder) %> |
<%= link_to 'Back', folders_path %>

app/views/folders/show.html.erb
<% if current_user %>

  <%= render 'sidebar', folder: @folder %>

  <main class="main">

    <h1>
      <%= @folder.name %>
      <% unless default_folder? %>
        <%= link_to edit_folder_path(@folder) do %>
          <%= inline_svg("edit-solid.svg") %>
          Edit
        <% end %>
      <% end %>
      </h1>

    <div id="articles" data-folder="<%= @folder.id %>">
      <% Array(@articles).each do |article| %>
        <div class="article" data-id="<%= article.id %>">
          <div class="sort-title-wrapper">
            <% unless current_page?(folder_path("archive")) %>
              <div class="sort">
                <%= inline_svg("sort-solid.svg") %>
              </div>
            <% end %>
            <div class="title-wrapper">
              <p class="title"><%= link_to article.title, article_path(article.id) %></p>
              <% if article.link.include? 'http' %>
                <p class="link"><%= url_only(article.link) %><%= link_to article.link, target: :_blank do %><%= inline_svg('external-link-alt-solid.svg') %><% end %></p>
              <% end %>
            </div>
          </div>
          <div class="archive-delete-wrapper">
            <% unless current_page?(folder_path("archive")) %>
              <%= link_to inline_svg("archive.svg"), archive_article_path(article), method: :patch, class: "archive", title: "Archive this Article" %>
            <% end %>
            <% unless current_page?(folder_path("unread")) %>
              <%= link_to inline_svg("home.svg"), unarchive_article_path(article), method: :patch, class: "archive", title: "Move to Unread Folder" %>
            <% end %>
            <%= link_to inline_svg("trash.svg"), article_path(article), method: :delete, data: { confirm: "Are you sure you want to permanently delete this article?" }, class: "delete", title: "Delete This Article" %>
          </div>
        </div>
      <% end %>
    </div>
    <%== pagy_nav(@pagy).html_safe if @pagy.pages > 1 %>
  </main>

<% else %>
  <main class="main">
    <%= render "layouts/signin" %>
  </main>
<% end %>