config/routes.rb
Rails.application.routes.draw do

  # root "folders#show"
  # root to: "folders#show", permalink: "unread"

  root to: redirect('/folder/unread')

  # devise_for :user
  devise_for :user,
  controllers: {
    registrations: 'users/registrations'
  },
  path: "",
  path_names: {
    sign_in: "login",
    sign_out: "logout",
    sign_up: "register",
    edit: "settings"
  }

  # get '/user', to: redirect('/folder/unread')

  get "folder/:permalink" => "folders#show", as: "folder_permalink"
  get "folder/:permalink/download" => "folders#download", as: "download_folder"
  patch "folder/:id/archive-all" => "folders#archive_all", as: "archive_all"
  resources :folders, path: "/folder" do
    member do
      patch :sort
    end
  end

  # get "article/new" => "article#create", as: "new_article"
  # delete "article/:permalink" => "article#destroy", as: "delete_article"
  # patch "article/:permalink/archive" => "article#archive", as: "archive_article"
  # patch "article/:permalink/unarchive" => "article#unarchive", as: "unarchive_article"
  resources :articles, path: "/article" do
    member do
      patch :archive
      patch :unarchive
    end
  end
  # resources :articles, only: [:index]
  get "export" => "articles#export", as: "export"

  namespace :hello, defaults: { format: 'js' } do
    # resources :articles
    get ":hello_token" => "articles#index"
    post ":hello_token" => "articles#create"
  end

  post "billing", to: "billing#create", as: "billing_create"
  post "billing/edit", to: "billing#edit", as: "billing_edit"
  resources :webhooks, only: [:create]

end

app/models/article.rb
require 'csv'

class Article < ApplicationRecord

  belongs_to :user
  belongs_to :folder

  validates :title, presence: true
  validates :link, presence: true, uniqueness: { scope: :user_id }

  # def self.to_csv
  #   CSV.generate(headers: true) do |csv|
  #     csv << ['URL', 'Title', 'Selection', 'Folder', 'Timestamp']
  #     all.each do |article|
  #       csv << [article.link, article.title, nil, article.folder.name, article.created_at.to_i]
  #     end
  #   end
  # end

  # The below is used for exporting to a non-Instapaper system

  def self.to_csv
    CSV.generate(headers: true) do |csv|
      csv << ['source_url', 'title', 'body', 'folder_id', 'created_at']
      all.each do |article|
        if article.folder.name == 'Unread'
          csv << [article.link, article.title, article.body, '1', article.created_at]
        elsif article.folder.name == 'Archive'
          csv << [article.link, article.title, article.body, '2', article.created_at]
        elsif article.folder.name == 'Dyslexia'
          csv << [article.link, article.title, article.body, '3', article.created_at]
        elsif article.folder.name == 'Dyslexia Archive'
          csv << [article.link, article.title, article.body, '4', article.created_at]
        elsif article.folder.name == 'Health Care'
          csv << [article.link, article.title, article.body, '5', article.created_at]
        elsif article.folder.name == 'Story Club'
          csv << [article.link, article.title, article.body, '6', article.created_at]
        elsif article.folder.name == 'Global Training Report'
          csv << [article.link, article.title, article.body, '7', article.created_at]
        end
      end
    end
  end

end

app/controllers/articles_controller.rb
require 'httparty'
require 'nokogiri'
require 'uri'

class ArticlesController < ApplicationController

  before_action :authenticate_user!
  # before_action :set_article_from_permalink, only: [:show, :edit, :update, :archive, :unarchive, :destroy]
  before_action :set_article, only: [:show, :edit, :update, :archive, :unarchive, :destroy]
  before_action :set_article_folder, only: :destroy

  # GET /articles
  # GET /articles.json
  # def index
  #   @articles = Article.all
  # end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @folder = Folder.find(@article.folder_id)
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create

    if is_numeric?(article_params[:link])
      @article = current_user.articles.new
      @article.link = article_params[:link]
      @article.user = current_user
      @article.folder_id = article_params[:folder_id]
      @article.title = article_params[:title]
      @article.body = article_params[:body]
      @article.position = current_user.articles.count
    else
      check_http_status(article_params[:link])
      clean_url = strip_utm_params(article_params[:link])
      # if link is already in database for this user, move it to home
      if current_user.articles.find_by_link(clean_url).present?
        @article = current_user.articles.find_by_link(clean_url)
        # Move the article in position 0 so this article can be in position 0
        first_article = current_user.articles.left_outer_joins(:folder).where(folder: { permalink: params[:permalink] }, position: 0)
        first_article.update(position: 1)
        folder = current_user.folders.find_by_name(params[:folder])
        @article.folder_id = folder.id
        @article.position = 0
      else
        @article = current_user.articles.new
        @article.link = clean_url
        @article.user = current_user
        folder = Folder.find_by(name: params[:folder], user_id: current_user.id)
        @article.folder_id = folder.id
        @article.title = get_title(clean_url)
        @article.body = ArticleFetch.download(@article)
        @article.position = current_user.articles.count
      end
    end

    @article.save!
    redirect_back fallback_location: folder_path("unread")
  rescue ActiveRecord::RecordInvalid, ActiveRecord::RecordNotSaved
    redirect_back fallback_location: folder_path("unread"), error: "Failed to save article.<br>This was an ActiveRecord error, not a `:link` error<br>#{@article.errors.full_messages}"
  rescue FetchError => error
    if URI.parse(clean_url).host.include? "bloomberg.com"
      error_message = "Bloomberg goes out of their way to break the internet. You will not be able to save this article."
    else
      error_message = "Error saving article. Check the URL and try again."
    end
    redirect_back fallback_location: folder_path("unread"), error: "#{error_message}<br>#{error}"
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH /articles/1/archive
  def archive
    folder = Folder.where(name: "Archive", user_id: current_user.id).first_or_create
    @article.folder_id = folder.id
    @article.save!
    redirect_back(fallback_location: folder_path)
  end

  # PATCH /articles/1/unarchive
  def unarchive
    current_user.articles.left_outer_joins(:folder).where(folder: { name: "Unread" }, position: 0).update(position: 1)
    @article.position = 0
    folder = Folder.where(name: "Unread", user_id: current_user.id).first_or_create
    @article.folder_id = folder.id
    @article.save!
    redirect_back(fallback_location: folder_path)
  end

  # GET /export.csv
  def export
    articles = current_user.articles
    respond_to do |format|
      format.html
      format.csv { send_data articles.to_csv, filename: "portholes-export-#{Date.today}.csv" }
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    redirect_to folder_path(@folder)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = current_user.articles.find(params[:id])
    end

    # def set_article_from_permalink
    #   article_id = Article.find_by!(permalink: params[:id], user_id: current_user.id).id
    #   @article = current_user.articles.find(article_id)
    # end
    #
    def set_article_folder
      article = Article.find_by!(id: params[:id], user_id: current_user.id)
      @folder = article.folder
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :link, :position, :user_id, :folder_id, :body)
    end

    # Check that the article is returning a 200 status code.
    def check_http_status(url)
      if HTTParty.get(url).response.code == '200'
        return
      else
        raise FetchError, "Article not found. Check the URL and try again."
      end
    rescue HTTParty::Error => error
      raise FetchError, error.to_s
    rescue StandardError => error
      raise FetchError, error.to_s
    end

end

app/controllers/hello/articles_controller.rb
require 'httparty'
require 'nokogiri'
require 'uri'

module Hello
  class ArticlesController < ApplicationController

    protect_from_forgery except: :index
    after_action :set_access_control_headers

    # TODO: find_by_hello_token should be changed. Something more secure like
    # current_user = User.find_by_session_id(session[:user_id])
    # Except find_by_session_id doesn't work if they're
    # not logged in. So a redirect to login would be needed.

    def index
      @current_user = User.find_by_hello_token(params[:hello_token])
      render content_type: "text/javascript"
    end

    def create
      current_user = User.find_by_hello_token(params[:hello_token])
      clean_url = strip_utm_params(params[:link])

      # if link is already in database for this user, move it to home
      if current_user.articles.find_by_link(clean_url).present?
        @article = current_user.articles.find_by_link(clean_url)
        # Move the article in position 0 so this article can be in position 0
        first_article = current_user.articles.left_outer_joins(:folder).where(folder: { permalink: "unread" }, position: 0)
        first_article.update(position: 1)
        folder = Folder.find_by(name: "Unread", user_id: current_user.id)
        folder_id = folder.id
        @article.folder_id = folder_id
        @article.position = 0
      else
        @article = current_user.articles.new(link: clean_url)
        @article.user = current_user
        folder = Folder.find_by(name: "Unread", user_id: current_user.id)
        folder_id = folder.id
        @article.folder_id = folder_id
        @article.title = get_title(clean_url)
        @article.body = ArticleFetch.download(@article)
        @article.position = current_user.articles.count
      end
      @article.save!
    end

    private

      def set_access_control_headers
        headers['Access-Control-Allow-Origin'] = '*'
        headers['Access-Control-Request-Method'] = 'POST'
      end

  end
end

app/helpers/articles_helper.rb
module ArticlesHelper

  def get_name_from_permalink(permalink)
    current_user.folders.find_by_permalink(permalink).name
  end

end

app/views/articles/_form.html.erb
<%= form_with(model: article, local: true, class: 'article-form') do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <% if params[:action] == 'new' %>
    <%= form.hidden_field :link, value: Article.last.id + 1 %>
  <% end %>

  <div class="field">
    <%= form.label :folder_id %>
    <% if params[:action] == 'new' %>
      <%= form.collection_select :folder_id, current_user.folders.order(:id), :id, :name %>
    <% else %>
      <%= form.collection_select :folder_id, current_user.folders.order(:name), :id, :name %>
    <% end %>
  </div>

  <% if params[:action] == 'edit' %>
    <div class="field">
      <%= form.label :link %>
      <%= form.text_field :link %>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, rows: 25 %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/_sidebar.html.erb
<aside class="sidebar">
  <nav class="widget">
    <% if article.link.include? 'http' %>
      <%= link_to article.link do %><%= inline_svg('external-link-alt-solid.svg') %>Original<% end %>
    <% end %>
    <%= link_to edit_article_path(article) do %><%= inline_svg('edit-solid.svg') %>Edit<% end %>
    <% unless article.folder.permalink == 'archive' %>
      <%= link_to archive_article_path(article), method: :patch do %><%= inline_svg("archive.svg") %>Archive<% end %>
    <% end %>
    <% unless article.folder.permalink == 'unread' %>
      <%= link_to unarchive_article_path(article), method: :patch do %><%= inline_svg("archive.svg") %>Unread<% end %>
    <% end %>
    <%= link_to article_path(article), method: :delete, data: { confirm: "Are you sure you want to permanently delete this article?" }, class: "delete" do %><%= inline_svg('trash.svg') %>Delete<% end %>
  </nav>
</aside>

app/views/articles/edit.html.erb
<%= render 'form', article: @article %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Articles</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Link</th>
      <th>Position</th>
      <th>User</th>
      <th>Folder</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.link %></td>
        <td><%= article.position %></td>
        <td><%= article.user_id %></td>
        <td><%= article.folder_id %></td>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

app/views/articles/show.html.erb
<%= render 'sidebar', article: @article %>

<main class="main">
  <article class="page">

    <header class="page__header">
      <h1 class="page__title"><%= @article.title %></h1>
    </header>

    <div class="page__content">
      <%= sanitize @article.body %>
    </div>

  </article>
</main>