config/routes.rb
Rails.application.routes.draw do

  # root "folders#show"
  # root to: "folders#show", permalink: "unread"

  root to: redirect('/folder/unread')

  # devise_for :user
  devise_for :user,
  controllers: {
    registrations: 'users/registrations'
  },
  path: "",
  path_names: {
    sign_in: "login",
    sign_out: "logout",
    sign_up: "register",
    edit: "settings"
  }

  # get '/user', to: redirect('/folder/unread')

  get "folder/:permalink" => "folders#show", as: "folder_permalink"
  get "folder/:permalink/download" => "folders#download", as: "download_folder"
  patch "folder/:id/archive-all" => "folders#archive_all", as: "archive_all"
  resources :folders, path: "/folder" do
    member do
      patch :sort
    end
  end

  # get "article/new" => "article#create", as: "new_article"
  # delete "article/:permalink" => "article#destroy", as: "delete_article"
  # patch "article/:permalink/archive" => "article#archive", as: "archive_article"
  # patch "article/:permalink/unarchive" => "article#unarchive", as: "unarchive_article"
  resources :articles, path: "/article" do
    member do
      patch :archive
      patch :unarchive
    end
  end
  # resources :articles, only: [:index]
  get "export" => "articles#export", as: "export"

  namespace :hello, defaults: { format: 'js' } do
    # resources :articles
    get ":hello_token" => "articles#index"
    post ":hello_token" => "articles#create"
  end

  post "billing", to: "billing#create", as: "billing_create"
  post "billing/edit", to: "billing#edit", as: "billing_edit"
  resources :webhooks, only: [:create]

end

app/views/layouts/_flash.html.erb
<% flash.each do |type, message| %>
  <% if message.present? %>
    <%= content_tag(:div, message.to_s.html_safe, class: "flash flash-#{type}") %>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title>Portholes</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body<% if params[:controller] == 'folders' %> class="sidebar-content"<% elsif params[:controller] == 'articles' %>  class="content-sidebar"<% end %>>

    <header class="site-header" itemscope itemtype="https://schema.org/WPHeader">

      <div class="title-area">
        <p class="site-title" itemprop="headline"><%= link_to "Portholes", folder_path("unread") %> RAILS</p>
      </div>

      <button class="responsive-menu-icon" aria-expanded="false" aria-controls="navigation">Menu</button>

      <nav class="navigation" id="navigation" itemscope itemtype="https://schema.org/SiteNavigationElement">
        <ul class="menu" data-collapsed="true">
          <% if user_signed_in? %>
            <li class="menu-item">
              <a id="add-link" class="button primary small" href="/add-link/"><%= inline_svg('plus-solid.svg') %>Add Link</a>
            </li>
            <li class="menu-item">
              <%= link_to(new_article_path, class: 'button primary small') do %><%= inline_svg('plus-solid.svg') %>Add Article<% end %>
            </li>
            <li class="menu-item">
              <a href="/navigation/" class="sub-menu-toggle" aria-expanded="false">
                <%= current_user.email %>
                <svg aria-hidden="true" focusable="false" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><path fill="currentColor" d="M207.029 381.476L12.686 187.132c-9.373-9.373-9.373-24.569 0-33.941l22.667-22.667c9.357-9.357 24.522-9.375 33.901-.04L224 284.505l154.745-154.021c9.379-9.335 24.544-9.317 33.901.04l22.667 22.667c9.373 9.373 9.373 24.569 0 33.941L240.971 381.476c-9.373 9.372-24.569 9.372-33.942 0z"></path></svg>
              </a>
              <ul class="sub-menu" data-collapsed="true">
                <% if downloadable_folder? %>
                  <li class="menu-item"><%= link_to("Download", download_folder_path) %></li>
                <% end %>
                <% if current_page?(folder_path("unread")) %>
                  <li class="menu-item"><a id="archive-all" href="/archive-all/" itemprop="url">Archive All</a></li>
                <% end %>
                <%= content_tag(:li, link_to("Settings", edit_user_registration_path), class: "menu-item") %>
                <%= content_tag(:li, link_to("Help & FAQ", "https://portholes.app/faq/"), class: "menu-item") %>
                <%= content_tag(:li, link_to("Log Out", destroy_user_session_path, method: :delete), class: "menu-item") %>
              </ul>
            </li>
          <% else %>
            <%= content_tag(:li, link_to("Log In", new_user_session_path), class: "menu-item") %>
            <%= content_tag(:li, link_to("Create Account", new_user_registration_path), class: "menu-item") %>
          <% end %>
        </ul>
      </nav>
    </header>

    <div class="site-inner">
      <%= render "layouts/flash" %>
      <%= yield %>
    </div>

    <div id="add-link-modal" class="modal add-link">
      <div class="modal__content">
        <div class="modal__header">
          Add a New Article
          <span class="modal__close" data-close="true" title="Close">&times;</span>
        </div>
        <div class="modal__body">
          <%= form_with(model: @article, url: articles_path, local: true, html: { class: 'article-add' }) do |form| %>
            <%= form.fields_for 'article' do |link| %>
              <%= link.label :link, class: "screen-reader-text" %>
              <%= link.text_field :link, class: "article-add__input" %>
            <% end %>
            <% if downloadable_folder? %>
              <%= hidden_field_tag 'folder', get_name_from_permalink(params[:permalink]) %>
            <% else %>
              <%= hidden_field_tag 'folder', 'Unread' %>
            <% end %>
            <%= form.submit "Add Article", class: "button primary" %>
          <% end %>
        </div>
      </div>
    </div>

  </body>

</html>